Extension update
Snail-IDE/snail-ide.github.io pull request #11
Opened 2023-12-07 03:02 UTC by thepython555

added 2 extensions and cleaned up some

2023-12-08 00:10 UTC, nmsderp requested changes
spMonitorsPlusIcon is declared but never used

2023-12-08 23:19 UTC, thepython555 commented
@nmsderp oops

2023-12-08 23:20 UTC, thepython555 commented
can you add the extension descriptions and pictures tho

2023-12-09 03:28 UTC, nmsderp commented
i fixed it and added the stuff to snail ide

2023-12-09 03:28 UTC, closed without merging